### ISSUE TITLE
register_network() not responding when registering from Belgium/Europe

### ISSUE THREAD

**Issue by mchobby** [sixfab/pico_lte_micropython-sdk#105]
Hi,
I have registered and activated my PicoLTE asset on the SixFab.com (and provided the required payment to get a positive balance).

I was trying to get the MQTT example at work but I got a connection issue on the Network.
```
>>> from pico_lte.utils.status import Status
>>> from pico_lte.core import PicoLTE
>>> from pico_lte.common import debug
>>> picoLTE  = PicoLTE()
```
Now, the red LED turns ON, the blue LED blinks shortly every 2 seconds.

Then, I call the `register_network()` which doens't return.

```
>>> picoLTE.network.register_network()
```

### Some additional tests
I did located the `debug` module but have not been able to get more information from it.

``` 
>>> picoLTE.network.get_apn()
{'status': 0, 'response': ['+CGDCONT: 1,"IPV4V6","super","0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0",0,0,0', 'OK'], 'value': 'super'}

>>> picoLTE.network.get_operator_information()
{'status': 0, 'response': ['+COPS: 0', 'OK'], 'value': '0'}

>>> picoLTE.network.base.get_all_cells()
{'response': 'timeout', 'status': 2}
```

I noticed that `get_all_cells()` takes time to respond (about 1 or 2 minutes) before returning a timeout.
It seems that the QueCTEL module cannot get registered on the mobile network.

Is there an easy way to spy the atcom messages exchange with the QueCTEL module ? 

Cheers
Dominique

**Comment by mchobby** [comment]
Please suspend this issue... after more that 15 minutes, the module get solid blue (with flash of every 3 seconds).
The register_network() now passed!

```
>>> picoLTE.network.register_network()
{'status': 0, 'response': ['+CREG: 0,5', 'OK'], 'interval': 0}
```

**Comment by ozgurkaraaslan** [comment]
LTE-CAT M1 network quality may be poor in your area. You can follow [this](https://docs.sixfab.com/docs/sixfab-pico-lte-troubleshooting#connection-time-too-long) and try to connect with GSM. If the problem persists, pls let us know.
