### ISSUE TITLE
examples/mqtt does not exist

### ISSUE THREAD

**Issue by schrockwell** [sixfab/pico_lte_micropython-sdk#106]
[The MQTT tutorial](https://docs.sixfab.com/docs/pico-lte-mqtt-example) mentions the `examples/mqtt` directory, but it doesn't exist in this repository.

The closest relevant example I can find is in `examples/thinkspeak`.

**Comment by ozgurkaraaslan** [comment]
@schrockwell The MQTT examples were located in the Dev branch; we have moved them to the Master branch. Thank you for the feedback.
