### ISSUE TITLE
Add authentication example / hint in http documentation.

### ISSUE THREAD

**Issue by georg90** [sixfab/pico_lte_micropython-sdk#108]
When scrolling through the documentation for HTTP(s) connection, it took me a while and some digging on GitHub to find out how to connect to an endpoint using basic authentication. I thought adding the `username` `password` to `config.json` is sufficient.

BUT, you need to run `picoLTE.http.set_auth()` additionally to set authentication. 

```
picoLTE = PicoLTE()

picoLTE.network.register_network()
picoLTE.http.set_context_id()
picoLTE.network.get_pdp_ready()
picoLTE.http.set_auth()
picoLTE.http.set_server_url()

debug.info("Sending a POST request.")
```

Maybe this can be added to the documentation, since one will usually use authentication with an public endpoint

https://docs.sixfab.com/docs/pico-lte-http-request-to-web-server

**Comment by ozgurkaraaslan** [comment]
Thank you very much for your feedback @georg90. We will update the document soon.

**Comment by ozgurkaraaslan** [comment]
Updated.
